### PR TITLE
add lazy collection support

### PR DESCRIPTION
**Pull request by Gummibeer**
solves #49

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
What would you think of using lazy collections everywhere and tagging v2?

**Comment by Gummibeer** [comment]
I've experienced ebad performance with lazy collections if used like normal ones.
There are several cases when normal collections are better. And I think that the cached sheets will improve several usecases. So only the ones when you only loop over all without needing all at the same time are more performant as lazy collection.
So I think that keeping them separated makes still sense.

**Comment by sebastiandedeyne** [comment]
Got it, sounds good 👍 

Want to pull this in, but I don't think I have permissions to solve the conflicts on your branch. Could you patch those up so I can merge?

**Comment by Gummibeer** [comment]
Sorry, forgot about it - are there still any conflicts? 🤔

**Comment by sebastiandedeyne** [comment]
Yes, iirc it's not compatible with your previous PR's.

**Comment by Gummibeer** [comment]
Don't worry - I will update it. 🙂

**Comment by Gummibeer** [comment]
@sebastiandedeyne have merged the current `spatie:master` and also updated the `all()` to don't duplicate the filter & map logic.

**Comment by sebastiandedeyne** [comment]
Thanks!

**Pull request merged**
